# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

entityList:
  - "BOSS_SLIME"
  - "SKELETON_MAGE"