# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "weaponSet_1"
  - "weaponSet_5"
  - "weaponSet_10"
  - "weaponSet_15"
  - "weaponSet_20"
  - "weaponSet_25"
  - "weaponSet_30"
  - "weaponSet_35"
  - "weaponSet_40"
  - "weaponSet_45"
  - "weaponSet_50"
  - "weaponSet_55"
  - "weaponSet_60"
  - "weaponSet_65"
  - "weaponSet_70"
  - "weaponSet_75"
  - "weaponSet_80"
  - "weaponSet_85"
  - "weaponSet_90"

