# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "weaponSet_1"
  - "weaponSet_2"
  - "weaponSet_3"
  - "weaponSet_4"
  - "weaponSet_5"

