# ---------------------------------------------- #
#             Egg list Configuration             #
# ---------------------------------------------- #
#                     Eggs                       #
# ---------------------------------------------- #

egg1:
  mythicMobCode: "CatAllBlack"
  customModelData: 6
  itemTier: "COMMON"
egg2:
  mythicMobCode: "ZombiePet"
  customModelData: 2
  itemTier: "RARE"