# ---------------------------------------------- #
#             Egg list Configuration             #
# ---------------------------------------------- #
#                     Eggs                       #
# ---------------------------------------------- #

egg1:
  mythicMobCode: "dsfdsfdsf"
  customModelData: 1
  itemTier: "COMMON"
egg2:
  mythicMobCode: "sdfsdfdsf"
  customModelData: 2
  itemTier: "RARE"
egg3:
  mythicMobCode: "sdfdsfsdf"
  customModelData: 2
  itemTier: "RARE"
  mountSpeed: 0.24