# ---------------------------------------------- #
#             Egg list Configuration             #
# ---------------------------------------------- #
#                     Eggs                       #
# ---------------------------------------------- #

egg1:
  mythicMobCode: "PetWolf"
  customModelData: 6
  itemTier: "COMMON"