# ---------------------------------------------- #
#             Egg list Configuration             #
# ---------------------------------------------- #
#                     Eggs                       #
# ---------------------------------------------- #

egg1:
  mythicMobCode: "CompanionWolf"
  customModelData: 6
  itemTier: "COMMON"
egg2:
  mythicMobCode: "MountTest"
  customModelData: 6
  itemTier: "COMMON"