# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "armorSet_1"
  - "armorSet_2"
  - "armorSet_3"

