# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

questLineList:
  - "tutorialQuests"
  - "1_academy"