# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "shieldSet_1"
  - "shieldSet_2"
  - "shieldSet_3"
  - "shieldSet_4"
  - "shieldSet_5"

