# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "shieldSet_1"
  - "shieldSet_5"
  - "shieldSet_10"
  - "shieldSet_15"
  - "shieldSet_20"
  - "shieldSet_25"
  - "shieldSet_30"
  - "shieldSet_35"
  - "shieldSet_40"
  - "shieldSet_45"
  - "shieldSet_50"
  - "shieldSet_55"
  - "shieldSet_60"
  - "shieldSet_65"
  - "shieldSet_70"
  - "shieldSet_75"
  - "shieldSet_80"
  - "shieldSet_85"
  - "shieldSet_90"

