# ---------------------------------------------- #
#             Class list Configuration           #
# ---------------------------------------------- #
#                    Classes                     #
# ---------------------------------------------- #

classList:
  - "warrior"
  - "archer"
  - "mage"
  - "hunter"