# ---------------------------------------------- #
#             Class list Configuration           #
# ---------------------------------------------- #
#                    Classes                     #
# ---------------------------------------------- #

classList:
  - "archer"
  - "hunter"
  - "knight"
  - "mage"
  - "monk"
  - "paladin"
  - "rogue"
  - "warrior"