# ---------------------------------------------- #
#             Class list Configuration           #
# ---------------------------------------------- #
#                    Classes                     #
# ---------------------------------------------- #

classList:
  - "archer"
  - "engineer"
  - "fire mage"
  - "frost mage"
  - "hunter"
  - "doom knight"
  - "monk"
  - "necromancer"
  - "paladin"
  - "reaper"
  - "shaman"
  - "dragonslayer"