# ---------------------------------------------- #
#             Class list Configuration           #
# ---------------------------------------------- #
#                    Classes                     #
# ---------------------------------------------- #

classTier1:
  requiredQuest: 3
classTier2:
  requiredQuest: 99
classTier3:
  requiredQuest: 999
classList:
  - "ranger"
  - "engineer"
  - "fire mage"
  - "frost mage"
  - "hunter"
  - "doom knight"
  - "monk"
  - "necromancer"
  - "paladin"
  - "reaper"
  - "shaman"
  - "dragonslayer"
  - "fighter"
  - "archer"
  - "novice mage"
  - "rogue"