# ---------------------------------------------- #
#             Class list Configuration           #
# ---------------------------------------------- #
#                    Classes                     #
# ---------------------------------------------- #

classList:
  - "warrior"