# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "passiveSet_1"
  - "passiveSet_2"
  - "passiveSet_3"

